name: PHP Deployment

on:
  push:
    branches:
      - main
      - td
  pull_request:
      branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host

      - name: Build Docker Image
        run: |
          docker build -t localhost:5000/sae:latest -f docker/Dockerfile .

      - name: Push Docker Image to Local Registry
        run: |
          docker push localhost:5000/sae:latest